### ISSUE TITLE
Documentation: How to provide C-grid u,v?

### ISSUE THREAD

**Issue by milankl** [JuliaClimate/IndividualDisplacements.jl#38]
Hey Gaël, going through the documentation, I find in most examples that you've hidden the explanation for how to set up the NamedTuple Parameter 𝑃 which contains field like `u0`,`u1`,`v0`,`v1` etc. in some underlying function like `𝑃,Γ=example2_setup()`. I'd assume that most users will have their velocity fields in some form, e.g. simply as julia array loaded from netcdf, so I'd be great to guide them how they can pass these arrays (which may be defined on a C-grid etc.) into IndividualDisplacements. 

Yes, you mention MeshArrays.jl, but unfortunately reading that documentation I still don't know how I can, for example, take data from ShallowWaters.jl and compute the particle trajectories. My idea was to test IndividualDisplacements against the semi-Lagrangian tracer advection scheme therein.

**Comment by milankl** [comment]
In the example for Single Particle you write `𝑃=(u0=uu, u1=uu, v0=vv, v1=vv,w0=0.0*w, w1=-0.01*w, 𝑇=[0,19.95*2*pi], ioSize=(np,np,nz))` but that's not entirely helpful either.

**Comment by milankl** [comment]
https://github.com/openjournals/joss-reviews/issues/2813

**Comment by milankl** [comment]
Maybe as a suggestion would it be possible to add something like

**Comment by milankl** [comment]
@gaelforget Could you provide some input to this issue, such that I can continue with the review?

**Comment by gaelforget** [comment]
> @gaelforget Could you provide some input to this issue, such that I can continue with the review?

Hi @milankl 

Sorry for delay. Have been working on it. More later today on this ...

**Comment by gaelforget** [comment]
Hi @milankl 

I have now added documentation to this effect [here](https://juliaclimate.github.io/IndividualDisplacements.jl/dev/examples/) and [here](https://juliaclimate.github.io/IndividualDisplacements.jl/dev/basics/random_flow_field/)

The approach you envisioned (generalizing MeshArray to support non-C grids) is certainly worth considering but would be more involved, so for now I opted for simply adding documentation here. 

Does this suffice to allow application to ShallowWaters.jl ? 

ps. I hope to spend more time on the docs this week, including the aforementioned sections

**Comment by milankl** [comment]
I'll look at it on Wednesday, thanks!

**Comment by milankl** [comment]
Hey Gaël, sorry for the delay. I think this issue is more general in a sense that you've buried some of the functionality in lines like this

**Comment by milankl** [comment]
Then I believe that some functionality as I already mentioned
> ```julia
> uv = MeshArray(u,v,x,y,grid-type=:C,geometry=:rectangle)
> I = Individuals(📌,🔴,uv)
> ```
would greatly increase the usability of this package. I guess ideally a user would want to have functions for three steps
- Provide velocity fields to IndividualDisplacements such they can be correctly interpreted
- Provide particle initial conditions
- Calculate trajectories
I see that you have the `∫!` and the `Individuals` functions for the last two steps, but then I don't understand why in the particle set tutorial you still pass the initial coordinates through the `setup_point_cloud` function?

**Comment by visr** [comment]
I'm running into the same issue wanting to apply this on a simple example grid of my own. I think the suggested syntax by @milankl could help here.

It's great to have many examples in the docs, but for me it seems the first tutorial (single particle) is too complicated. It would be best if it can be self explanatory, with no code being included from separate files. How about something super simple like this?

```julia
using Plots

X = range(0, 2π, length=60)
Y = range(0, π, length=30)
f(x, y) = sin(x) + cos(y)
ϕ = [f(x, y) for y in Y, x in X]
u = [cos(x) for y in Y, x in X]
v = [sin(y) for y in Y, x in X]

heatmap(X, Y, ϕ)
```
![image](https://user-images.githubusercontent.com/4471859/102698106-33883400-423b-11eb-99b6-9cf6c7900fec.png)

This would be a static 2D example. A next step could be adding a phase to show how this would work over time.

**Comment by gaelforget** [comment]
> I'm running into the same issue wanting to apply this on a simple example grid of my own. I think the suggested syntax by @milankl could help here.
> 
> It's great to have many examples in the docs, but for me it seems the first tutorial (single particle) is too complicated. It would be best if it can be self explanatory, with no code being included from separate files. How about something super simple like this?
> 
> ```julia
> using Plots
> 
> X = range(0, 2π, length=60)
> Y = range(0, π, length=30)
> f(x, y) = sin(x) + cos(y)
> ϕ = [f(x, y) for y in Y, x in X]
> u = [cos(x) for y in Y, x in X]
> v = [sin(y) for y in Y, x in X]
> 
> heatmap(X, Y, ϕ)
> ```
> 
> ![image](https://user-images.githubusercontent.com/4471859/102698106-33883400-423b-11eb-99b6-9cf6c7900fec.png)
> 
> This would be a static 2D example. A next step could be adding a phase to show how this would work over time.

Hi @visr 

Fair enough. 

I have now revamped the second example (random flow field) using the suggested streamfunction as I understood it (below w. a tunable factor added) and promoted it to appear as the first example in the docs.

```
fac=0.1
f(x, y) = sin(x) + cos(y) #streamfunction
ϕ = fac*[f(x, y) for x in XC,y in YC] #streamfunction
uC = -fac*[sin(y) for x in XC,y in YC] #dphi/dy at cell center
vC = -fac*[cos(x) for x in XC,y in YC]; #-dphi/dx at cell center
```

This simplicity saves the need for calling an external function like `random_flow_field` or `solid_body_rotation` to define a more complicated flow field. Other flow field definition functions used the examples have been gathered in `examples/flow_fields.jl` (also aiming to make things more clear).

The data structure constructor calls was also inlined in `random_flow_field.jl` so that every function the user calls in the example is readily inlined or obtained from the package module (constructors). This degree of simplification was enabled by the code modifications done in version `0.2.7` to `0.2.9`. 

A couple more aspects that I should mention about the revamped `examples/basics/random_flow_field.jl`
- the staggering of variables for the C-grid and grid scale and normalization to grid point units (which were not done in your above comment, or indeed sufficiently explained in the docs) are now also directly embedded in the now first example found in the docs
- this first example now uses plain Array rather than MeshArray by default; the optional code though shows how to switch between Array and MeshArray

The syntax is a bit different from the one suggested by @milankl but I am hoping that `examples/basics/random_flow_field.jl` (now the first example in the docs) achieves the intended goal.

Does this work?

**Comment by gaelforget** [comment]
> Hey Gaël, going through the documentation, I find in most examples that you've hidden the explanation for how to set up the NamedTuple Parameter 𝑃 which contains field like `u0`,`u1`,`v0`,`v1` etc. in some underlying function like `𝑃,Γ=example2_setup()`. I'd assume that most users will have their velocity fields in some form, e.g. simply as julia array loaded from netcdf, so I'd be great to guide them how they can pass these arrays (which may be defined on a C-grid etc.) into IndividualDisplacements.
> 
> Yes, you mention MeshArrays.jl, but unfortunately reading that documentation I still don't know how I can, for example, take data from ShallowWaters.jl and compute the particle trajectories. My idea was to test IndividualDisplacements against the semi-Lagrangian tracer advection scheme therein.

Hi @milankl 

Fair enough. 

Please refer to https://github.com/JuliaClimate/IndividualDisplacements.jl/issues/38#issuecomment-774256677 for additional detail as well as the updated docs about constructors.

Let me just get to the bottom line first if that's ok -- the application to `ShallowWaters.jl` now reduces to something like:

```
using ShallowWaters
Prog = RunModel(Float32,Ndays=10,g=10,H=500,Fx0=0.12,output=true)

u=Prog.u
v=Prog.v
η=Prog.η
𝑇=[0.0,864000.0]
dx=20000.0

using IndividualDisplacements

𝐹=𝐹_Array2D(u/dx,u/dx,v/dx,v/dx,𝑇)

(np,nq)=size(u)
x=np*(0.4 .+ 0.2*rand(100))
y=nq*(0.4 .+ 0.2*rand(100));

𝐼=Individuals(𝐹,x,y)

∫!(𝐼)
```

and for plotting, e.g.:

```
p=dirname(pathof(IndividualDisplacements))
include(joinpath(p,"../examples/recipes_plots.jl"));

🔴_by_t = groupby(𝐼.🔴, :t)
anim = @animate for t in eachindex(🔴_by_t)
   phi_scatter(η,🔴_by_t[t])
end

pth=tempdir()*"/"
gif(anim, pth*"ShallowWaters.gif", fps = 10)
```

The normalization by dx is as documented in the first example found in the docs (`examples/basics/random_flow_field.jl`) and temporal interpolation between velocity fields is readily provided by the `FlowFields` constructors + e.g. NetCDF.jl to read output from ShallowWaters.jl

```
u=ncread("run0000/u.nc","u")[:,:,end]
v=ncread("run0000/v.nc","v")[:,:,end]
η=ncread("run0000/eta.nc","eta")[:,:,end]
t=ncread("run0000/u.nc","t")
𝑇=Float64.(t[end-1:end])
```

Does this work?

**Comment by gaelforget** [comment]
> Then I believe that some functionality as I already mentioned
> 
> > ```julia
> > uv = MeshArray(u,v,x,y,grid-type=:C,geometry=:rectangle)
> > I = Individuals(📌,🔴,uv)
> > ```
> 
> would greatly increase the usability of this package. I guess ideally a user would want to have functions for three steps
> 
> * Provide velocity fields to IndividualDisplacements such they can be correctly interpreted
> * Provide particle initial conditions
> * Calculate trajectories
> 
> I see that you have the `∫!` and the `Individuals` functions for the last two steps, but then I don't understand why in the particle set tutorial you still pass the initial coordinates through the `setup_point_cloud` function?

Thanks for the feedback and suggestions. 

I have now streamlined step 1 further so that in rectangular domain case (the most common one maybe) it amounts to calling the corresponding `FlowFields` constructor for plain Arrays (`𝐹_Array2D`). Interpolation from grid-cell center to C-grid velocity points (at grid cell edges) and normalization by grid scale factors are simple Array operations in this case -- as documented in e.g. `random_flow_field.jl` now. 

The more general case of global C-grids commonly used in climate models is when something like `MeshArrays.jl` can greatly facilitate gridded data manipulations which new users often struggle with in my experience. I tried to document these aspects as effectively as possible via the examples, but feel that moving some of the data munging steps to separate file (e.g. flow_fields.jl) improves different levels of reading of the docs.

So my hope is that "How to provide C-grid u,v?" is now sufficiently well addressed in the examples / docs and that this issue can therefore be closed.

Would you agree?

ps. At this point (incl. based on recent developments discussed in this thread) I believe that `IndividualDisplacements` will provide a solid basis for even more generalization in the future. In fact, one may hope that extensions to other grid topologies (or `grid-type` / `geometry` in your words) via `MeshArrays.jl` (or other packages) could occur relatively soon. But, I would also say that this goes beyond the current, stated, scope of `IndividualDisplacements.jl`

**Comment by milankl** [comment]
Thanks @gaelforget for the work you've put in here. Yes, I think the docs show now nicely how this can be done. I'll close this issue for now.
