### ISSUE TITLE
CubeSphere vs LatLonCap

### ISSUE THREAD

**Issue by milankl** [JuliaClimate/IndividualDisplacements.jl#42]
https://github.com/JuliaClimate/IndividualDisplacements.jl/blob/7a5df040c6674013deb461f5fe6bd3feb21d3ba4/src/compute.jl#L27-L28

Is there a type here and you actually want to call a function like `update_location_llc` or similar in L28? Otherwise the branching doesn't make much sense...

**Comment by milankl** [comment]
https://github.com/openjournals/joss-reviews/issues/2813

**Comment by gaelforget** [comment]
They actually do the same thing because the face connections that matter are set up the same way (as highlighted by the color scheme in Fig 1 of https://doi.org/10.5194/gmd-8-3071-2015 ) while face connections on Antartica  do not need to be represented for the llc grid since this is an ocean only grid (unlike cube sphere which makes sense for the Atmosphere and Ocean). I know this is tricky ... 

In any event, I introduced an alias for `update_location_llc!` to make it more clear that this is not a bug

**Comment by milankl** [comment]
Great, good to know, I never worked with LLC...
